name: atma_cinema
description: "An app for easy movie ticket booking with real-time seat selection
    and secure payment."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.1

dependencies:
    camera: ^0.11.0+2
    carousel_slider: ^5.0.0
    dotted_border: ^2.1.0
    flutter:
        sdk: flutter
    flutter_dash: ^1.0.0
    flutter_native_splash: ^2.4.1
    flutter_riverpod: ^2.6.1
    flutter_secure_storage: ^9.2.2
    flutter_svg: ^2.0.10+1
    google_fonts: ^6.2.1
    google_sign_in: ^6.2.2
    http: ^1.2.2
    image_picker: ^1.1.2
    intl: ^0.19.0
    material_symbols_icons: ^4.2785.1
    path_provider: ^2.1.5
    pdf: ^3.6.5
    photo_manager: ^3.6.0
    printing: ^5.7.2
    qr_flutter: ^4.1.0
    screenshot: ^3.0.0
    share_plus: ^10.1.3
    skeletonizer: ^1.4.2
    smooth_page_indicator: ^1.2.0+3
    speech_to_text: ^7.0.0
    uuid: ^4.5.1
    video_player: ^2.5.0

dev_dependencies:
    flutter_lints: ^4.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - images/
        - images/ac_logo.png
        - images/fnb/
